
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.capitalmode.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.capitalmode.item.YeuxdechatItem;
import net.mcreator.capitalmode.item.UnEUItem;
import net.mcreator.capitalmode.item.UltimastoneItem;
import net.mcreator.capitalmode.item.TravelItem;
import net.mcreator.capitalmode.item.SugiliteSwordItem;
import net.mcreator.capitalmode.item.SugiliteShovelItem;
import net.mcreator.capitalmode.item.SugilitePickaxeItem;
import net.mcreator.capitalmode.item.SugiliteItem;
import net.mcreator.capitalmode.item.SugiliteHoeItem;
import net.mcreator.capitalmode.item.SugiliteAxeItem;
import net.mcreator.capitalmode.item.SugiliteArmorItem;
import net.mcreator.capitalmode.item.SpeedstoneItem;
import net.mcreator.capitalmode.item.SpeedpickaxeItem;
import net.mcreator.capitalmode.item.SpeedSwordItem;
import net.mcreator.capitalmode.item.SoulSwordItem;
import net.mcreator.capitalmode.item.RubyItem;
import net.mcreator.capitalmode.item.RubiSwordItem;
import net.mcreator.capitalmode.item.RubiShovelItem;
import net.mcreator.capitalmode.item.RubiPickaxeItem;
import net.mcreator.capitalmode.item.RubiHoeItem;
import net.mcreator.capitalmode.item.RubiAxeItem;
import net.mcreator.capitalmode.item.RubiArmorItem;
import net.mcreator.capitalmode.item.ReliquesacItem;
import net.mcreator.capitalmode.item.ReliquepvpItem;
import net.mcreator.capitalmode.item.ReliquefireItem;
import net.mcreator.capitalmode.item.ReliqueeauItem;
import net.mcreator.capitalmode.item.ReliqueboofItem;
import net.mcreator.capitalmode.item.PuissancedemoniaqueItem;
import net.mcreator.capitalmode.item.PetitssoinsItem;
import net.mcreator.capitalmode.item.PerfectCoalItem;
import net.mcreator.capitalmode.item.NetheriterankItem;
import net.mcreator.capitalmode.item.MilleeuroItem;
import net.mcreator.capitalmode.item.JouetmarteauItem;
import net.mcreator.capitalmode.item.IronrankItem;
import net.mcreator.capitalmode.item.IridiumspeedswordItem;
import net.mcreator.capitalmode.item.IridiumspeedpickaxeItem;
import net.mcreator.capitalmode.item.IridiumseedItem;
import net.mcreator.capitalmode.item.IridiumrankItem;
import net.mcreator.capitalmode.item.IridiumpowderItem;
import net.mcreator.capitalmode.item.IridiumhammerItem;
import net.mcreator.capitalmode.item.IridiumbigswordItem;
import net.mcreator.capitalmode.item.IridfonduItem;
import net.mcreator.capitalmode.item.InvisiblearmorItem;
import net.mcreator.capitalmode.item.Hyperactif3Item;
import net.mcreator.capitalmode.item.Hyperactif2Item;
import net.mcreator.capitalmode.item.Hyperactif1Item;
import net.mcreator.capitalmode.item.GrandcoeurItem;
import net.mcreator.capitalmode.item.Grandcoeur3Item;
import net.mcreator.capitalmode.item.Grandcoeur2Item;
import net.mcreator.capitalmode.item.GoldRankItem;
import net.mcreator.capitalmode.item.GiverreliqueItem;
import net.mcreator.capitalmode.item.FirestoneItem;
import net.mcreator.capitalmode.item.DolomiteingotItem;
import net.mcreator.capitalmode.item.DixeuroItem;
import net.mcreator.capitalmode.item.DiamondrankItem;
import net.mcreator.capitalmode.item.DemonworldItem;
import net.mcreator.capitalmode.item.DemonHearsItem;
import net.mcreator.capitalmode.item.DeadstoneItem;
import net.mcreator.capitalmode.item.CosmetiquecobspeedswordItem;
import net.mcreator.capitalmode.item.CobgdagueItem;
import net.mcreator.capitalmode.item.CobaltspeedswordItem;
import net.mcreator.capitalmode.item.CobaltspeedpickaxeItem;
import net.mcreator.capitalmode.item.CobaltseedItem;
import net.mcreator.capitalmode.item.CobaltrankItem;
import net.mcreator.capitalmode.item.CobaltpowderItem;
import net.mcreator.capitalmode.item.CobaltfonduItem;
import net.mcreator.capitalmode.item.CobaltbigwordItem;
import net.mcreator.capitalmode.item.CobaltHammerItem;
import net.mcreator.capitalmode.item.CoalrankItem;
import net.mcreator.capitalmode.item.CinquannteEUItem;
import net.mcreator.capitalmode.item.CinqcenEUItem;
import net.mcreator.capitalmode.item.ChutelibreItem;
import net.mcreator.capitalmode.item.CentEUItem;
import net.mcreator.capitalmode.item.CapitalwandItem;
import net.mcreator.capitalmode.item.CapitalstickItem;
import net.mcreator.capitalmode.item.CapitalspearItem;
import net.mcreator.capitalmode.item.CapitalseedItem;
import net.mcreator.capitalmode.item.CapitalrankItem;
import net.mcreator.capitalmode.item.CapitalpowderItem;
import net.mcreator.capitalmode.item.CapitalhammerItem;
import net.mcreator.capitalmode.item.CapitalfonduItem;
import net.mcreator.capitalmode.item.CapitaleArmorItem;
import net.mcreator.capitalmode.item.CapitaldagueItem;
import net.mcreator.capitalmode.item.CapitalappleItem;
import net.mcreator.capitalmode.item.Capital_outilsSwordItem;
import net.mcreator.capitalmode.item.Capital_outilsShovelItem;
import net.mcreator.capitalmode.item.Capital_outilsPickaxeItem;
import net.mcreator.capitalmode.item.Capital_outilsHoeItem;
import net.mcreator.capitalmode.item.Capital_outilsAxeItem;
import net.mcreator.capitalmode.item.CapitalItem;
import net.mcreator.capitalmode.item.CapitalFauxItem;
import net.mcreator.capitalmode.item.BourredeflechesItem;
import net.mcreator.capitalmode.item.BionicswordItem;
import net.mcreator.capitalmode.item.BigswordItem;
import net.mcreator.capitalmode.item.BatterieexterneItem;
import net.mcreator.capitalmode.item.BatoniriduimItem;
import net.mcreator.capitalmode.item.BandageItem;
import net.mcreator.capitalmode.item.Ameliorateurniv6itemItem;
import net.mcreator.capitalmode.item.Ameliorateurlvl9Item;
import net.mcreator.capitalmode.item.Ameliorateurlvl8Item;
import net.mcreator.capitalmode.item.Ameliorateurlvl7Item;
import net.mcreator.capitalmode.item.Ameliorateurlvl5Item;
import net.mcreator.capitalmode.item.Ameliorateurlvl4Item;
import net.mcreator.capitalmode.item.Ameliorateurlvl3Item;
import net.mcreator.capitalmode.item.Ameliorateurlvl2Item;
import net.mcreator.capitalmode.item.Ameliorateurlvl10Item;
import net.mcreator.capitalmode.item.AmeliorastoneItem;
import net.mcreator.capitalmode.item.AchatchunkItem;
import net.mcreator.capitalmode.CapitalModeMod;

public class CapitalModeModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, CapitalModeMod.MODID);
	public static final RegistryObject<Item> CAPITAL = REGISTRY.register("capital", () -> new CapitalItem());
	public static final RegistryObject<Item> CAPITAL_ORE = block(CapitalModeModBlocks.CAPITAL_ORE);
	public static final RegistryObject<Item> CAPITAL_OUTILS_PICKAXE = REGISTRY.register("capital_outils_pickaxe", () -> new Capital_outilsPickaxeItem());
	public static final RegistryObject<Item> CAPITAL_OUTILS_AXE = REGISTRY.register("capital_outils_axe", () -> new Capital_outilsAxeItem());
	public static final RegistryObject<Item> CAPITAL_OUTILS_SWORD = REGISTRY.register("capital_outils_sword", () -> new Capital_outilsSwordItem());
	public static final RegistryObject<Item> CAPITAL_OUTILS_SHOVEL = REGISTRY.register("capital_outils_shovel", () -> new Capital_outilsShovelItem());
	public static final RegistryObject<Item> CAPITAL_OUTILS_HOE = REGISTRY.register("capital_outils_hoe", () -> new Capital_outilsHoeItem());
	public static final RegistryObject<Item> CAPITALE_ARMOR_HELMET = REGISTRY.register("capitale_armor_helmet", () -> new CapitaleArmorItem.Helmet());
	public static final RegistryObject<Item> CAPITALE_ARMOR_CHESTPLATE = REGISTRY.register("capitale_armor_chestplate", () -> new CapitaleArmorItem.Chestplate());
	public static final RegistryObject<Item> CAPITALE_ARMOR_LEGGINGS = REGISTRY.register("capitale_armor_leggings", () -> new CapitaleArmorItem.Leggings());
	public static final RegistryObject<Item> CAPITALE_ARMOR_BOOTS = REGISTRY.register("capitale_armor_boots", () -> new CapitaleArmorItem.Boots());
	public static final RegistryObject<Item> CAPITALAPPLE = REGISTRY.register("capitalapple", () -> new CapitalappleItem());
	public static final RegistryObject<Item> DEMON_HEARS = REGISTRY.register("demon_hears", () -> new DemonHearsItem());
	public static final RegistryObject<Item> COBALT = REGISTRY.register("cobalt", () -> new RubyItem());
	public static final RegistryObject<Item> RUBI_PICKAXE = REGISTRY.register("rubi_pickaxe", () -> new RubiPickaxeItem());
	public static final RegistryObject<Item> RUBI_AXE = REGISTRY.register("rubi_axe", () -> new RubiAxeItem());
	public static final RegistryObject<Item> RUBI_SWORD = REGISTRY.register("rubi_sword", () -> new RubiSwordItem());
	public static final RegistryObject<Item> RUBI_SHOVEL = REGISTRY.register("rubi_shovel", () -> new RubiShovelItem());
	public static final RegistryObject<Item> RUBI_HOE = REGISTRY.register("rubi_hoe", () -> new RubiHoeItem());
	public static final RegistryObject<Item> RUBI_ARMOR_HELMET = REGISTRY.register("rubi_armor_helmet", () -> new RubiArmorItem.Helmet());
	public static final RegistryObject<Item> RUBI_ARMOR_CHESTPLATE = REGISTRY.register("rubi_armor_chestplate", () -> new RubiArmorItem.Chestplate());
	public static final RegistryObject<Item> RUBI_ARMOR_LEGGINGS = REGISTRY.register("rubi_armor_leggings", () -> new RubiArmorItem.Leggings());
	public static final RegistryObject<Item> RUBI_ARMOR_BOOTS = REGISTRY.register("rubi_armor_boots", () -> new RubiArmorItem.Boots());
	public static final RegistryObject<Item> CAPITALSTICK = REGISTRY.register("capitalstick", () -> new CapitalstickItem());
	public static final RegistryObject<Item> CABLOCK = block(CapitalModeModBlocks.CABLOCK);
	public static final RegistryObject<Item> COBLOCK = block(CapitalModeModBlocks.COBLOCK);
	public static final RegistryObject<Item> UN_EU = REGISTRY.register("un_eu", () -> new UnEUItem());
	public static final RegistryObject<Item> DIXEURO = REGISTRY.register("dixeuro", () -> new DixeuroItem());
	public static final RegistryObject<Item> CINQUANNTE_EU = REGISTRY.register("cinquannte_eu", () -> new CinquannteEUItem());
	public static final RegistryObject<Item> CENT_EU = REGISTRY.register("cent_eu", () -> new CentEUItem());
	public static final RegistryObject<Item> CINQCEN_EU = REGISTRY.register("cinqcen_eu", () -> new CinqcenEUItem());
	public static final RegistryObject<Item> AMELIORATEURLVL_2 = REGISTRY.register("ameliorateurlvl_2", () -> new Ameliorateurlvl2Item());
	public static final RegistryObject<Item> AMELIORATEURLVL_3 = REGISTRY.register("ameliorateurlvl_3", () -> new Ameliorateurlvl3Item());
	public static final RegistryObject<Item> AMELIORATEURLVL_4 = REGISTRY.register("ameliorateurlvl_4", () -> new Ameliorateurlvl4Item());
	public static final RegistryObject<Item> AMELIORATEURLVL_5 = REGISTRY.register("ameliorateurlvl_5", () -> new Ameliorateurlvl5Item());
	public static final RegistryObject<Item> SPEED_SWORD = REGISTRY.register("speed_sword", () -> new SpeedSwordItem());
	public static final RegistryObject<Item> CAPITAL_MACHINE = block(CapitalModeModBlocks.CAPITAL_MACHINE);
	public static final RegistryObject<Item> AMELIORASTONE = REGISTRY.register("ameliorastone", () -> new AmeliorastoneItem());
	public static final RegistryObject<Item> SPEEDSTONE = REGISTRY.register("speedstone", () -> new SpeedstoneItem());
	public static final RegistryObject<Item> SPEEDPICKAXE = REGISTRY.register("speedpickaxe", () -> new SpeedpickaxeItem());
	public static final RegistryObject<Item> CAPITALHAMMER = REGISTRY.register("capitalhammer", () -> new CapitalhammerItem());
	public static final RegistryObject<Item> CAPITALWAND = REGISTRY.register("capitalwand", () -> new CapitalwandItem());
	public static final RegistryObject<Item> ULTIMASTONE = REGISTRY.register("ultimastone", () -> new UltimastoneItem());
	public static final RegistryObject<Item> BIGSWORD = REGISTRY.register("bigsword", () -> new BigswordItem());
	public static final RegistryObject<Item> AMELIORATEURNIV_6ITEM = REGISTRY.register("ameliorateurniv_6item", () -> new Ameliorateurniv6itemItem());
	public static final RegistryObject<Item> COBALT_HAMMER = REGISTRY.register("cobalt_hammer", () -> new CobaltHammerItem());
	public static final RegistryObject<Item> COBALTSPEEDSWORD = REGISTRY.register("cobaltspeedsword", () -> new CobaltspeedswordItem());
	public static final RegistryObject<Item> COBALTBIGWORD = REGISTRY.register("cobaltbigword", () -> new CobaltbigwordItem());
	public static final RegistryObject<Item> COBALTSPEEDPICKAXE = REGISTRY.register("cobaltspeedpickaxe", () -> new CobaltspeedpickaxeItem());
	public static final RegistryObject<Item> AMELIORATEURLVL_7 = REGISTRY.register("ameliorateurlvl_7", () -> new Ameliorateurlvl7Item());
	public static final RegistryObject<Item> MILLEEURO = REGISTRY.register("milleeuro", () -> new MilleeuroItem());
	public static final RegistryObject<Item> AMELIORATEURLVL_9 = REGISTRY.register("ameliorateurlvl_9", () -> new Ameliorateurlvl9Item());
	public static final RegistryObject<Item> AMELIORATEURLVL_8 = REGISTRY.register("ameliorateurlvl_8", () -> new Ameliorateurlvl8Item());
	public static final RegistryObject<Item> SUGILITE_BLOCK = block(CapitalModeModBlocks.SUGILITE_BLOCK);
	public static final RegistryObject<Item> SUGILITE_PICKAXE = REGISTRY.register("sugilite_pickaxe", () -> new SugilitePickaxeItem());
	public static final RegistryObject<Item> SUGILITE_SHOVEL = REGISTRY.register("sugilite_shovel", () -> new SugiliteShovelItem());
	public static final RegistryObject<Item> SUGILITE_AXE = REGISTRY.register("sugilite_axe", () -> new SugiliteAxeItem());
	public static final RegistryObject<Item> SUGILITE = REGISTRY.register("sugilite", () -> new SugiliteItem());
	public static final RegistryObject<Item> SUGILITE_ARMOR_HELMET = REGISTRY.register("sugilite_armor_helmet", () -> new SugiliteArmorItem.Helmet());
	public static final RegistryObject<Item> SUGILITE_ARMOR_CHESTPLATE = REGISTRY.register("sugilite_armor_chestplate", () -> new SugiliteArmorItem.Chestplate());
	public static final RegistryObject<Item> SUGILITE_ARMOR_LEGGINGS = REGISTRY.register("sugilite_armor_leggings", () -> new SugiliteArmorItem.Leggings());
	public static final RegistryObject<Item> SUGILITE_ARMOR_BOOTS = REGISTRY.register("sugilite_armor_boots", () -> new SugiliteArmorItem.Boots());
	public static final RegistryObject<Item> SUGILITE_SWORD = REGISTRY.register("sugilite_sword", () -> new SugiliteSwordItem());
	public static final RegistryObject<Item> SUGILITE_HOE = REGISTRY.register("sugilite_hoe", () -> new SugiliteHoeItem());
	public static final RegistryObject<Item> AMELIORATEURLVL_10 = REGISTRY.register("ameliorateurlvl_10", () -> new Ameliorateurlvl10Item());
	public static final RegistryObject<Item> FONDERIE = block(CapitalModeModBlocks.FONDERIE);
	public static final RegistryObject<Item> CAPITALFONDU_BUCKET = REGISTRY.register("capitalfondu_bucket", () -> new CapitalfonduItem());
	public static final RegistryObject<Item> BATONIRIDUIM = REGISTRY.register("batoniriduim", () -> new BatoniriduimItem());
	public static final RegistryObject<Item> ACHATCHUNK = REGISTRY.register("achatchunk", () -> new AchatchunkItem());
	public static final RegistryObject<Item> PERFECT_COAL = REGISTRY.register("perfect_coal", () -> new PerfectCoalItem());
	public static final RegistryObject<Item> CONDENSEDSTONE = block(CapitalModeModBlocks.CONDENSEDSTONE);
	public static final RegistryObject<Item> ULTRACONDENSED = block(CapitalModeModBlocks.ULTRACONDENSED);
	public static final RegistryObject<Item> COBALTFONDU_BUCKET = REGISTRY.register("cobaltfondu_bucket", () -> new CobaltfonduItem());
	public static final RegistryObject<Item> CAPITALPOWDER = REGISTRY.register("capitalpowder", () -> new CapitalpowderItem());
	public static final RegistryObject<Item> COBALTPOWDER = REGISTRY.register("cobaltpowder", () -> new CobaltpowderItem());
	public static final RegistryObject<Item> IRIDIUMPOWDER = REGISTRY.register("iridiumpowder", () -> new IridiumpowderItem());
	public static final RegistryObject<Item> IRIDFONDU_BUCKET = REGISTRY.register("iridfondu_bucket", () -> new IridfonduItem());
	public static final RegistryObject<Item> DEADSTONE = REGISTRY.register("deadstone", () -> new DeadstoneItem());
	public static final RegistryObject<Item> CAPITAL_FAUX = REGISTRY.register("capital_faux", () -> new CapitalFauxItem());
	public static final RegistryObject<Item> COBGDAGUE = REGISTRY.register("cobgdague", () -> new CobgdagueItem());
	public static final RegistryObject<Item> CAPITALDAGUE = REGISTRY.register("capitaldague", () -> new CapitaldagueItem());
	public static final RegistryObject<Item> FIRESTONE = REGISTRY.register("firestone", () -> new FirestoneItem());
	public static final RegistryObject<Item> IRIDIUMSPEEDSWORD = REGISTRY.register("iridiumspeedsword", () -> new IridiumspeedswordItem());
	public static final RegistryObject<Item> CAPITALSPEAR = REGISTRY.register("capitalspear", () -> new CapitalspearItem());
	public static final RegistryObject<Item> IRIDIUMHAMMER = REGISTRY.register("iridiumhammer", () -> new IridiumhammerItem());
	public static final RegistryObject<Item> IRIDIUMSPEEDPICKAXE = REGISTRY.register("iridiumspeedpickaxe", () -> new IridiumspeedpickaxeItem());
	public static final RegistryObject<Item> RELIQUEEAU = REGISTRY.register("reliqueeau", () -> new ReliqueeauItem());
	public static final RegistryObject<Item> RELIQUEBOOF = REGISTRY.register("reliqueboof", () -> new ReliqueboofItem());
	public static final RegistryObject<Item> RELIQUESAC = REGISTRY.register("reliquesac", () -> new ReliquesacItem());
	public static final RegistryObject<Item> RELIQUEFIRE = REGISTRY.register("reliquefire", () -> new ReliquefireItem());
	public static final RegistryObject<Item> RELIQUEPVP = REGISTRY.register("reliquepvp", () -> new ReliquepvpItem());
	public static final RegistryObject<Item> ROUEDUGARDIEN = REGISTRY.register("rouedugardien", () -> new GiverreliqueItem());
	public static final RegistryObject<Item> JOUETMARTEAU = REGISTRY.register("jouetmarteau", () -> new JouetmarteauItem());
	public static final RegistryObject<Item> IRIDIUMBIGSWORD = REGISTRY.register("iridiumbigsword", () -> new IridiumbigswordItem());
	public static final RegistryObject<Item> INVOCATEUR = block(CapitalModeModBlocks.INVOCATEUR);
	public static final RegistryObject<Item> DEMONWORLD = REGISTRY.register("demonworld", () -> new DemonworldItem());
	public static final RegistryObject<Item> GRANDCOEUR = REGISTRY.register("grandcoeur", () -> new GrandcoeurItem());
	public static final RegistryObject<Item> FANDECAPITAL = block(CapitalModeModBlocks.FANDECAPITAL);
	public static final RegistryObject<Item> BOURREDEFLECHES = REGISTRY.register("bourredefleches", () -> new BourredeflechesItem());
	public static final RegistryObject<Item> HYPERACTIF_1 = REGISTRY.register("hyperactif_1", () -> new Hyperactif1Item());
	public static final RegistryObject<Item> HYPERACTIF_2 = REGISTRY.register("hyperactif_2", () -> new Hyperactif2Item());
	public static final RegistryObject<Item> HYPERACTIF_3 = REGISTRY.register("hyperactif_3", () -> new Hyperactif3Item());
	public static final RegistryObject<Item> YEUXDECHAT = REGISTRY.register("yeuxdechat", () -> new YeuxdechatItem());
	public static final RegistryObject<Item> GRANDCOEUR_2 = REGISTRY.register("grandcoeur_2", () -> new Grandcoeur2Item());
	public static final RegistryObject<Item> GRANDCOEUR_3 = REGISTRY.register("grandcoeur_3", () -> new Grandcoeur3Item());
	public static final RegistryObject<Item> PETITSSOINS = REGISTRY.register("petitssoins", () -> new PetitssoinsItem());
	public static final RegistryObject<Item> CHUTELIBRE = REGISTRY.register("chutelibre", () -> new ChutelibreItem());
	public static final RegistryObject<Item> CAPITALSEED = REGISTRY.register("capitalseed", () -> new CapitalseedItem());
	public static final RegistryObject<Item> CAPITALPLANT = block(CapitalModeModBlocks.CAPITALPLANT);
	public static final RegistryObject<Item> CAPITALPLANT_2 = block(CapitalModeModBlocks.CAPITALPLANT_2);
	public static final RegistryObject<Item> CAPITALPLANT_3 = block(CapitalModeModBlocks.CAPITALPLANT_3);
	public static final RegistryObject<Item> CAPITALPLANT_4 = block(CapitalModeModBlocks.CAPITALPLANT_4);
	public static final RegistryObject<Item> DOLOMITEINGOT = REGISTRY.register("dolomiteingot", () -> new DolomiteingotItem());
	public static final RegistryObject<Item> INVISIBLEARMOR_HELMET = REGISTRY.register("invisiblearmor_helmet", () -> new InvisiblearmorItem.Helmet());
	public static final RegistryObject<Item> INVISIBLEARMOR_CHESTPLATE = REGISTRY.register("invisiblearmor_chestplate", () -> new InvisiblearmorItem.Chestplate());
	public static final RegistryObject<Item> INVISIBLEARMOR_LEGGINGS = REGISTRY.register("invisiblearmor_leggings", () -> new InvisiblearmorItem.Leggings());
	public static final RegistryObject<Item> INVISIBLEARMOR_BOOTS = REGISTRY.register("invisiblearmor_boots", () -> new InvisiblearmorItem.Boots());
	public static final RegistryObject<Item> DOLOMITEORE = block(CapitalModeModBlocks.DOLOMITEORE);
	public static final RegistryObject<Item> SOUL_SWORD = REGISTRY.register("soul_sword", () -> new SoulSwordItem());
	public static final RegistryObject<Item> ELECTRICFURNACE = block(CapitalModeModBlocks.ELECTRICFURNACE);
	public static final RegistryObject<Item> SUPER_COBALT_OLD_SWORD = REGISTRY.register("super_cobalt_old_sword", () -> new CosmetiquecobspeedswordItem());
	public static final RegistryObject<Item> PANNEAUSOLAIR = block(CapitalModeModBlocks.PANNEAUSOLAIR);
	public static final RegistryObject<Item> DIMENSIONALMACHINE = block(CapitalModeModBlocks.DIMENSIONALMACHINE);
	public static final RegistryObject<Item> BOXCOMMUNE = block(CapitalModeModBlocks.BOXCOMMUNE);
	public static final RegistryObject<Item> PUISSANCEDEMONIAQUE = REGISTRY.register("puissancedemoniaque", () -> new PuissancedemoniaqueItem());
	public static final RegistryObject<Item> DYNAMO = block(CapitalModeModBlocks.DYNAMO);
	public static final RegistryObject<Item> MINERALYSER = block(CapitalModeModBlocks.MINERALYSER);
	public static final RegistryObject<Item> BATTERIE = block(CapitalModeModBlocks.BATTERIE);
	public static final RegistryObject<Item> COAL_RANK = REGISTRY.register("coal_rank", () -> new CoalrankItem());
	public static final RegistryObject<Item> MOUETTE_SPAWN_EGG = REGISTRY.register("mouette_spawn_egg", () -> new ForgeSpawnEggItem(CapitalModeModEntities.MOUETTE, -3355444, -16737895, new Item.Properties()));
	public static final RegistryObject<Item> IRIDIUM_RANK = REGISTRY.register("iridium_rank", () -> new IridiumrankItem());
	public static final RegistryObject<Item> GOLD_RANK = REGISTRY.register("gold_rank", () -> new GoldRankItem());
	public static final RegistryObject<Item> COBALT_RANK = REGISTRY.register("cobalt_rank", () -> new CobaltrankItem());
	public static final RegistryObject<Item> DIAMOND_RANK = REGISTRY.register("diamond_rank", () -> new DiamondrankItem());
	public static final RegistryObject<Item> IRON_RANK = REGISTRY.register("iron_rank", () -> new IronrankItem());
	public static final RegistryObject<Item> NETHERITE_RANK = REGISTRY.register("netherite_rank", () -> new NetheriterankItem());
	public static final RegistryObject<Item> CAPITAL_RANK = REGISTRY.register("capital_rank", () -> new CapitalrankItem());
	public static final RegistryObject<Item> BANDAGE = REGISTRY.register("bandage", () -> new BandageItem());
	public static final RegistryObject<Item> DEMON_SPAWN_EGG = REGISTRY.register("demon_spawn_egg", () -> new ForgeSpawnEggItem(CapitalModeModEntities.DEMON, -16777216, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> GARDIENDEMONIAQUE_SPAWN_EGG = REGISTRY.register("gardiendemoniaque_spawn_egg", () -> new ForgeSpawnEggItem(CapitalModeModEntities.GARDIENDEMONIAQUE, -16777216, -52429, new Item.Properties()));
	public static final RegistryObject<Item> AUTEL_DEMONIAQUE = block(CapitalModeModBlocks.AUTEL_DEMONIAQUE);
	public static final RegistryObject<Item> ATM = block(CapitalModeModBlocks.ATM);
	public static final RegistryObject<Item> COBALTSEED = REGISTRY.register("cobaltseed", () -> new CobaltseedItem());
	public static final RegistryObject<Item> COBALTPLANT = block(CapitalModeModBlocks.COBALTPLANT);
	public static final RegistryObject<Item> COBALTPLANT_2 = block(CapitalModeModBlocks.COBALTPLANT_2);
	public static final RegistryObject<Item> COBALTPLANT_3 = block(CapitalModeModBlocks.COBALTPLANT_3);
	public static final RegistryObject<Item> COBALTPLANT_4 = block(CapitalModeModBlocks.COBALTPLANT_4);
	public static final RegistryObject<Item> IRIDIUMSEED = REGISTRY.register("iridiumseed", () -> new IridiumseedItem());
	public static final RegistryObject<Item> IRIDIUMPLANT = block(CapitalModeModBlocks.IRIDIUMPLANT);
	public static final RegistryObject<Item> IRIDIUMPLANT_2 = block(CapitalModeModBlocks.IRIDIUMPLANT_2);
	public static final RegistryObject<Item> IRIDIUMPLANT_3 = block(CapitalModeModBlocks.IRIDIUMPLANT_3);
	public static final RegistryObject<Item> IRIDIUMPLANT_4 = block(CapitalModeModBlocks.IRIDIUMPLANT_4);
	public static final RegistryObject<Item> DOLOMITE_FARMLAND = block(CapitalModeModBlocks.DOLOMITE_FARMLAND);
	public static final RegistryObject<Item> QUARRY = block(CapitalModeModBlocks.QUARRY);
	public static final RegistryObject<Item> LIMITES = block(CapitalModeModBlocks.LIMITES);
	public static final RegistryObject<Item> CAPITALE = block(CapitalModeModBlocks.CAPITALE);
	public static final RegistryObject<Item> BUEGRASS = block(CapitalModeModBlocks.BUEGRASS);
	public static final RegistryObject<Item> CABLE = block(CapitalModeModBlocks.CABLE);
	public static final RegistryObject<Item> CABLEE = block(CapitalModeModBlocks.CABLEE);
	public static final RegistryObject<Item> CABLEI = block(CapitalModeModBlocks.CABLEI);
	public static final RegistryObject<Item> CABLEL = block(CapitalModeModBlocks.CABLEL);
	public static final RegistryObject<Item> CABLE_LC = block(CapitalModeModBlocks.CABLE_LC);
	public static final RegistryObject<Item> CABLE_LCC = block(CapitalModeModBlocks.CABLE_LCC);
	public static final RegistryObject<Item> CABLE_LT = block(CapitalModeModBlocks.CABLE_LT);
	public static final RegistryObject<Item> CABLE_LTC = block(CapitalModeModBlocks.CABLE_LTC);
	public static final RegistryObject<Item> CABLE_T = block(CapitalModeModBlocks.CABLE_T);
	public static final RegistryObject<Item> CABLE_TC = block(CapitalModeModBlocks.CABLE_TC);
	public static final RegistryObject<Item> CABLE_TX = block(CapitalModeModBlocks.CABLE_TX);
	public static final RegistryObject<Item> CABLE_TXC = block(CapitalModeModBlocks.CABLE_TXC);
	public static final RegistryObject<Item> CABLE_TXCC = block(CapitalModeModBlocks.CABLE_TXCC);
	public static final RegistryObject<Item> CABLE_X = block(CapitalModeModBlocks.CABLE_X);
	public static final RegistryObject<Item> CABLE_XC = block(CapitalModeModBlocks.CABLE_XC);
	public static final RegistryObject<Item> CABLE_F = block(CapitalModeModBlocks.CABLE_F);
	public static final RegistryObject<Item> CABLE_S = block(CapitalModeModBlocks.CABLE_S);
	public static final RegistryObject<Item> TRAVEL_HELMET = REGISTRY.register("travel_helmet", () -> new TravelItem.Helmet());
	public static final RegistryObject<Item> TRAVEL_CHESTPLATE = REGISTRY.register("travel_chestplate", () -> new TravelItem.Chestplate());
	public static final RegistryObject<Item> TRAVEL_LEGGINGS = REGISTRY.register("travel_leggings", () -> new TravelItem.Leggings());
	public static final RegistryObject<Item> TRAVEL_BOOTS = REGISTRY.register("travel_boots", () -> new TravelItem.Boots());
	public static final RegistryObject<Item> LUMIERE = block(CapitalModeModBlocks.LUMIERE);
	public static final RegistryObject<Item> BIONICSWORD = REGISTRY.register("bionicsword", () -> new BionicswordItem());
	public static final RegistryObject<Item> BATTERIEEXTERNE = REGISTRY.register("batterieexterne", () -> new BatterieexterneItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
