
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.capitalmode.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.capitalmode.block.UltracondensedBlock;
import net.mcreator.capitalmode.block.SugiliteBlockBlock;
import net.mcreator.capitalmode.block.QuarryBlock;
import net.mcreator.capitalmode.block.PanneausolairBlock;
import net.mcreator.capitalmode.block.MineralyserBlock;
import net.mcreator.capitalmode.block.LumiereBlock;
import net.mcreator.capitalmode.block.LimitesBlock;
import net.mcreator.capitalmode.block.IridiumplantBlock;
import net.mcreator.capitalmode.block.Iridiumplant4Block;
import net.mcreator.capitalmode.block.Iridiumplant3Block;
import net.mcreator.capitalmode.block.Iridiumplant2Block;
import net.mcreator.capitalmode.block.IridfonduBlock;
import net.mcreator.capitalmode.block.InvocateurBlock;
import net.mcreator.capitalmode.block.FonderieBlock;
import net.mcreator.capitalmode.block.FandecapitalBlock;
import net.mcreator.capitalmode.block.ElectricfurnaceBlock;
import net.mcreator.capitalmode.block.DynamoBlock;
import net.mcreator.capitalmode.block.DolomiteoreBlock;
import net.mcreator.capitalmode.block.DolomiteFarmlandBlock;
import net.mcreator.capitalmode.block.DimensionalmachineBlock;
import net.mcreator.capitalmode.block.DemonworldPortalBlock;
import net.mcreator.capitalmode.block.CondensedstoneBlock;
import net.mcreator.capitalmode.block.CoblockBlock;
import net.mcreator.capitalmode.block.CobaltplantBlock;
import net.mcreator.capitalmode.block.Cobaltplant4Block;
import net.mcreator.capitalmode.block.Cobaltplant3Block;
import net.mcreator.capitalmode.block.Cobaltplant2Block;
import net.mcreator.capitalmode.block.CobaltfonduBlock;
import net.mcreator.capitalmode.block.CapitalplantBlock;
import net.mcreator.capitalmode.block.Capitalplant4Block;
import net.mcreator.capitalmode.block.Capitalplant3Block;
import net.mcreator.capitalmode.block.Capitalplant2Block;
import net.mcreator.capitalmode.block.CapitaloreBlock;
import net.mcreator.capitalmode.block.CapitalfonduBlock;
import net.mcreator.capitalmode.block.CapitaleBlock;
import net.mcreator.capitalmode.block.CapitalMachineBlock;
import net.mcreator.capitalmode.block.CablockBlock;
import net.mcreator.capitalmode.block.CablelBlock;
import net.mcreator.capitalmode.block.CableiBlock;
import net.mcreator.capitalmode.block.CableeBlock;
import net.mcreator.capitalmode.block.CableXCBlock;
import net.mcreator.capitalmode.block.CableXBlock;
import net.mcreator.capitalmode.block.CableTXCCBlock;
import net.mcreator.capitalmode.block.CableTXCBlock;
import net.mcreator.capitalmode.block.CableTXBlock;
import net.mcreator.capitalmode.block.CableTCBlock;
import net.mcreator.capitalmode.block.CableTBlock;
import net.mcreator.capitalmode.block.CableSBlock;
import net.mcreator.capitalmode.block.CableLTCBlock;
import net.mcreator.capitalmode.block.CableLTBlock;
import net.mcreator.capitalmode.block.CableLCCBlock;
import net.mcreator.capitalmode.block.CableLCBlock;
import net.mcreator.capitalmode.block.CableFBlock;
import net.mcreator.capitalmode.block.CableBlock;
import net.mcreator.capitalmode.block.BuegrassBlock;
import net.mcreator.capitalmode.block.BoxcommuneBlock;
import net.mcreator.capitalmode.block.BatterieBlock;
import net.mcreator.capitalmode.block.AutelDemoniaqueBlock;
import net.mcreator.capitalmode.block.ATMBlock;
import net.mcreator.capitalmode.CapitalModeMod;

public class CapitalModeModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, CapitalModeMod.MODID);
	public static final RegistryObject<Block> CAPITAL_ORE = REGISTRY.register("capital_ore", () -> new CapitaloreBlock());
	public static final RegistryObject<Block> CABLOCK = REGISTRY.register("cablock", () -> new CablockBlock());
	public static final RegistryObject<Block> COBLOCK = REGISTRY.register("coblock", () -> new CoblockBlock());
	public static final RegistryObject<Block> CAPITAL_MACHINE = REGISTRY.register("capital_machine", () -> new CapitalMachineBlock());
	public static final RegistryObject<Block> SUGILITE_BLOCK = REGISTRY.register("sugilite_block", () -> new SugiliteBlockBlock());
	public static final RegistryObject<Block> FONDERIE = REGISTRY.register("fonderie", () -> new FonderieBlock());
	public static final RegistryObject<Block> CAPITALFONDU = REGISTRY.register("capitalfondu", () -> new CapitalfonduBlock());
	public static final RegistryObject<Block> CONDENSEDSTONE = REGISTRY.register("condensedstone", () -> new CondensedstoneBlock());
	public static final RegistryObject<Block> ULTRACONDENSED = REGISTRY.register("ultracondensed", () -> new UltracondensedBlock());
	public static final RegistryObject<Block> COBALTFONDU = REGISTRY.register("cobaltfondu", () -> new CobaltfonduBlock());
	public static final RegistryObject<Block> IRIDFONDU = REGISTRY.register("iridfondu", () -> new IridfonduBlock());
	public static final RegistryObject<Block> INVOCATEUR = REGISTRY.register("invocateur", () -> new InvocateurBlock());
	public static final RegistryObject<Block> DEMONWORLD_PORTAL = REGISTRY.register("demonworld_portal", () -> new DemonworldPortalBlock());
	public static final RegistryObject<Block> FANDECAPITAL = REGISTRY.register("fandecapital", () -> new FandecapitalBlock());
	public static final RegistryObject<Block> CAPITALPLANT = REGISTRY.register("capitalplant", () -> new CapitalplantBlock());
	public static final RegistryObject<Block> CAPITALPLANT_2 = REGISTRY.register("capitalplant_2", () -> new Capitalplant2Block());
	public static final RegistryObject<Block> CAPITALPLANT_3 = REGISTRY.register("capitalplant_3", () -> new Capitalplant3Block());
	public static final RegistryObject<Block> CAPITALPLANT_4 = REGISTRY.register("capitalplant_4", () -> new Capitalplant4Block());
	public static final RegistryObject<Block> DOLOMITEORE = REGISTRY.register("dolomiteore", () -> new DolomiteoreBlock());
	public static final RegistryObject<Block> ELECTRICFURNACE = REGISTRY.register("electricfurnace", () -> new ElectricfurnaceBlock());
	public static final RegistryObject<Block> PANNEAUSOLAIR = REGISTRY.register("panneausolair", () -> new PanneausolairBlock());
	public static final RegistryObject<Block> DIMENSIONALMACHINE = REGISTRY.register("dimensionalmachine", () -> new DimensionalmachineBlock());
	public static final RegistryObject<Block> BOXCOMMUNE = REGISTRY.register("boxcommune", () -> new BoxcommuneBlock());
	public static final RegistryObject<Block> DYNAMO = REGISTRY.register("dynamo", () -> new DynamoBlock());
	public static final RegistryObject<Block> MINERALYSER = REGISTRY.register("mineralyser", () -> new MineralyserBlock());
	public static final RegistryObject<Block> BATTERIE = REGISTRY.register("batterie", () -> new BatterieBlock());
	public static final RegistryObject<Block> AUTEL_DEMONIAQUE = REGISTRY.register("autel_demoniaque", () -> new AutelDemoniaqueBlock());
	public static final RegistryObject<Block> ATM = REGISTRY.register("atm", () -> new ATMBlock());
	public static final RegistryObject<Block> COBALTPLANT = REGISTRY.register("cobaltplant", () -> new CobaltplantBlock());
	public static final RegistryObject<Block> COBALTPLANT_2 = REGISTRY.register("cobaltplant_2", () -> new Cobaltplant2Block());
	public static final RegistryObject<Block> COBALTPLANT_3 = REGISTRY.register("cobaltplant_3", () -> new Cobaltplant3Block());
	public static final RegistryObject<Block> COBALTPLANT_4 = REGISTRY.register("cobaltplant_4", () -> new Cobaltplant4Block());
	public static final RegistryObject<Block> IRIDIUMPLANT = REGISTRY.register("iridiumplant", () -> new IridiumplantBlock());
	public static final RegistryObject<Block> IRIDIUMPLANT_2 = REGISTRY.register("iridiumplant_2", () -> new Iridiumplant2Block());
	public static final RegistryObject<Block> IRIDIUMPLANT_3 = REGISTRY.register("iridiumplant_3", () -> new Iridiumplant3Block());
	public static final RegistryObject<Block> IRIDIUMPLANT_4 = REGISTRY.register("iridiumplant_4", () -> new Iridiumplant4Block());
	public static final RegistryObject<Block> DOLOMITE_FARMLAND = REGISTRY.register("dolomite_farmland", () -> new DolomiteFarmlandBlock());
	public static final RegistryObject<Block> QUARRY = REGISTRY.register("quarry", () -> new QuarryBlock());
	public static final RegistryObject<Block> LIMITES = REGISTRY.register("limites", () -> new LimitesBlock());
	public static final RegistryObject<Block> CAPITALE = REGISTRY.register("capitale", () -> new CapitaleBlock());
	public static final RegistryObject<Block> BUEGRASS = REGISTRY.register("buegrass", () -> new BuegrassBlock());
	public static final RegistryObject<Block> CABLE = REGISTRY.register("cable", () -> new CableBlock());
	public static final RegistryObject<Block> CABLEE = REGISTRY.register("cablee", () -> new CableeBlock());
	public static final RegistryObject<Block> CABLEI = REGISTRY.register("cablei", () -> new CableiBlock());
	public static final RegistryObject<Block> CABLEL = REGISTRY.register("cablel", () -> new CablelBlock());
	public static final RegistryObject<Block> CABLE_LC = REGISTRY.register("cable_lc", () -> new CableLCBlock());
	public static final RegistryObject<Block> CABLE_LCC = REGISTRY.register("cable_lcc", () -> new CableLCCBlock());
	public static final RegistryObject<Block> CABLE_LT = REGISTRY.register("cable_lt", () -> new CableLTBlock());
	public static final RegistryObject<Block> CABLE_LTC = REGISTRY.register("cable_ltc", () -> new CableLTCBlock());
	public static final RegistryObject<Block> CABLE_T = REGISTRY.register("cable_t", () -> new CableTBlock());
	public static final RegistryObject<Block> CABLE_TC = REGISTRY.register("cable_tc", () -> new CableTCBlock());
	public static final RegistryObject<Block> CABLE_TX = REGISTRY.register("cable_tx", () -> new CableTXBlock());
	public static final RegistryObject<Block> CABLE_TXC = REGISTRY.register("cable_txc", () -> new CableTXCBlock());
	public static final RegistryObject<Block> CABLE_TXCC = REGISTRY.register("cable_txcc", () -> new CableTXCCBlock());
	public static final RegistryObject<Block> CABLE_X = REGISTRY.register("cable_x", () -> new CableXBlock());
	public static final RegistryObject<Block> CABLE_XC = REGISTRY.register("cable_xc", () -> new CableXCBlock());
	public static final RegistryObject<Block> CABLE_F = REGISTRY.register("cable_f", () -> new CableFBlock());
	public static final RegistryObject<Block> CABLE_S = REGISTRY.register("cable_s", () -> new CableSBlock());
	public static final RegistryObject<Block> LUMIERE = REGISTRY.register("lumiere", () -> new LumiereBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
