/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.capitalmode.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.capitalmode.item.*;
import net.mcreator.capitalmode.block.FandecapitalBlock;
import net.mcreator.capitalmode.CapitalModeMod;

import java.util.function.Function;

public class CapitalModeModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(CapitalModeMod.MODID);
	public static final DeferredItem<Item> CAPITAL;
	public static final DeferredItem<Item> CAPITAL_ORE;
	public static final DeferredItem<Item> CAPITAL_OUTILS_PICKAXE;
	public static final DeferredItem<Item> CAPITAL_OUTILS_AXE;
	public static final DeferredItem<Item> CAPITAL_OUTILS_SWORD;
	public static final DeferredItem<Item> CAPITAL_OUTILS_SHOVEL;
	public static final DeferredItem<Item> CAPITAL_OUTILS_HOE;
	public static final DeferredItem<Item> CAPITALE_ARMOR_HELMET;
	public static final DeferredItem<Item> CAPITALE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> CAPITALE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> CAPITALE_ARMOR_BOOTS;
	public static final DeferredItem<Item> CAPITALAPPLE;
	public static final DeferredItem<Item> COBALT;
	public static final DeferredItem<Item> RUBI_PICKAXE;
	public static final DeferredItem<Item> RUBI_AXE;
	public static final DeferredItem<Item> RUBI_SWORD;
	public static final DeferredItem<Item> RUBI_SHOVEL;
	public static final DeferredItem<Item> RUBI_HOE;
	public static final DeferredItem<Item> RUBI_ARMOR_HELMET;
	public static final DeferredItem<Item> RUBI_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> RUBI_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> RUBI_ARMOR_BOOTS;
	public static final DeferredItem<Item> CAPITALSTICK;
	public static final DeferredItem<Item> CABLOCK;
	public static final DeferredItem<Item> COBLOCK;
	public static final DeferredItem<Item> UN_EU;
	public static final DeferredItem<Item> DIXEURO;
	public static final DeferredItem<Item> CINQUANNTE_EU;
	public static final DeferredItem<Item> CENT_EU;
	public static final DeferredItem<Item> CINQCEN_EU;
	public static final DeferredItem<Item> AMELIORATEURLVL_2;
	public static final DeferredItem<Item> AMELIORATEURLVL_3;
	public static final DeferredItem<Item> AMELIORATEURLVL_4;
	public static final DeferredItem<Item> AMELIORATEURLVL_5;
	public static final DeferredItem<Item> SPEED_SWORD;
	public static final DeferredItem<Item> CAPITAL_MACHINE;
	public static final DeferredItem<Item> AMELIORASTONE;
	public static final DeferredItem<Item> SPEEDSTONE;
	public static final DeferredItem<Item> SPEEDPICKAXE;
	public static final DeferredItem<Item> CAPITALHAMMER;
	public static final DeferredItem<Item> CAPITALWAND;
	public static final DeferredItem<Item> ULTIMASTONE;
	public static final DeferredItem<Item> BIGSWORD;
	public static final DeferredItem<Item> AMELIORATEURNIV_6ITEM;
	public static final DeferredItem<Item> COBALT_HAMMER;
	public static final DeferredItem<Item> COBALTSPEEDSWORD;
	public static final DeferredItem<Item> COBALTBIGWORD;
	public static final DeferredItem<Item> COBALTSPEEDPICKAXE;
	public static final DeferredItem<Item> AMELIORATEURLVL_7;
	public static final DeferredItem<Item> MILLEEURO;
	public static final DeferredItem<Item> AMELIORATEURLVL_9;
	public static final DeferredItem<Item> AMELIORATEURLVL_8;
	public static final DeferredItem<Item> SUGILITE_BLOCK;
	public static final DeferredItem<Item> SUGILITE_PICKAXE;
	public static final DeferredItem<Item> SUGILITE_SHOVEL;
	public static final DeferredItem<Item> SUGILITE_AXE;
	public static final DeferredItem<Item> SUGILITE;
	public static final DeferredItem<Item> SUGILITE_ARMOR_HELMET;
	public static final DeferredItem<Item> SUGILITE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SUGILITE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SUGILITE_ARMOR_BOOTS;
	public static final DeferredItem<Item> SUGILITE_SWORD;
	public static final DeferredItem<Item> SUGILITE_HOE;
	public static final DeferredItem<Item> AMELIORATEURLVL_10;
	public static final DeferredItem<Item> FONDERIE;
	public static final DeferredItem<Item> CAPITALFONDU_BUCKET;
	public static final DeferredItem<Item> BATONIRIDUIM;
	public static final DeferredItem<Item> ACHATCHUNK;
	public static final DeferredItem<Item> PERFECT_COAL;
	public static final DeferredItem<Item> COBALTFONDU_BUCKET;
	public static final DeferredItem<Item> CAPITALPOWDER;
	public static final DeferredItem<Item> COBALTPOWDER;
	public static final DeferredItem<Item> IRIDIUMPOWDER;
	public static final DeferredItem<Item> IRIDFONDU_BUCKET;
	public static final DeferredItem<Item> DEADSTONE;
	public static final DeferredItem<Item> CAPITAL_FAUX;
	public static final DeferredItem<Item> COBGDAGUE;
	public static final DeferredItem<Item> CAPITALDAGUE;
	public static final DeferredItem<Item> FIRESTONE;
	public static final DeferredItem<Item> IRIDIUMSPEEDSWORD;
	public static final DeferredItem<Item> CAPITALSPEAR;
	public static final DeferredItem<Item> IRIDIUMHAMMER;
	public static final DeferredItem<Item> IRIDIUMSPEEDPICKAXE;
	public static final DeferredItem<Item> IRIDIUMBIGSWORD;
	public static final DeferredItem<Item> GRANDCOEUR;
	public static final DeferredItem<Item> FANDECAPITAL;
	public static final DeferredItem<Item> BOURREDEFLECHES;
	public static final DeferredItem<Item> HYPERACTIF_1;
	public static final DeferredItem<Item> HYPERACTIF_2;
	public static final DeferredItem<Item> HYPERACTIF_3;
	public static final DeferredItem<Item> YEUXDECHAT;
	public static final DeferredItem<Item> GRANDCOEUR_2;
	public static final DeferredItem<Item> GRANDCOEUR_3;
	public static final DeferredItem<Item> PETITSSOINS;
	public static final DeferredItem<Item> CHUTELIBRE;
	public static final DeferredItem<Item> CAPITALSEED;
	public static final DeferredItem<Item> CAPITALPLANT;
	public static final DeferredItem<Item> CAPITALPLANT_2;
	public static final DeferredItem<Item> CAPITALPLANT_3;
	public static final DeferredItem<Item> CAPITALPLANT_4;
	public static final DeferredItem<Item> DOLOMITEINGOT;
	public static final DeferredItem<Item> DOLOMITEORE;
	public static final DeferredItem<Item> ELECTRICFURNACE;
	public static final DeferredItem<Item> DIMENSIONALMACHINE;
	public static final DeferredItem<Item> PUISSANCEDEMONIAQUE;
	public static final DeferredItem<Item> BATTERIE;
	public static final DeferredItem<Item> COAL_RANK;
	public static final DeferredItem<Item> IRIDIUM_RANK;
	public static final DeferredItem<Item> GOLD_RANK;
	public static final DeferredItem<Item> COBALT_RANK;
	public static final DeferredItem<Item> DIAMOND_RANK;
	public static final DeferredItem<Item> IRON_RANK;
	public static final DeferredItem<Item> NETHERITE_RANK;
	public static final DeferredItem<Item> CAPITAL_RANK;
	public static final DeferredItem<Item> BANDAGE;
	public static final DeferredItem<Item> ATM;
	public static final DeferredItem<Item> COBALTSEED;
	public static final DeferredItem<Item> COBALTPLANT;
	public static final DeferredItem<Item> COBALTPLANT_2;
	public static final DeferredItem<Item> COBALTPLANT_3;
	public static final DeferredItem<Item> COBALTPLANT_4;
	public static final DeferredItem<Item> IRIDIUMSEED;
	public static final DeferredItem<Item> IRIDIUMPLANT;
	public static final DeferredItem<Item> IRIDIUMPLANT_2;
	public static final DeferredItem<Item> IRIDIUMPLANT_3;
	public static final DeferredItem<Item> IRIDIUMPLANT_4;
	public static final DeferredItem<Item> DOLOMITE_FARMLAND;
	public static final DeferredItem<Item> QUARRY;
	public static final DeferredItem<Item> LIMITES;
	public static final DeferredItem<Item> CAPITALE;
	public static final DeferredItem<Item> BIONICSWORD;
	public static final DeferredItem<Item> BATTERIEEXTERNE;
	static {
		CAPITAL = register("capital", CapitalItem::new);
		CAPITAL_ORE = block(CapitalModeModBlocks.CAPITAL_ORE);
		CAPITAL_OUTILS_PICKAXE = register("capital_outils_pickaxe", Capital_outilsPickaxeItem::new);
		CAPITAL_OUTILS_AXE = register("capital_outils_axe", Capital_outilsAxeItem::new);
		CAPITAL_OUTILS_SWORD = register("capital_outils_sword", Capital_outilsSwordItem::new);
		CAPITAL_OUTILS_SHOVEL = register("capital_outils_shovel", Capital_outilsShovelItem::new);
		CAPITAL_OUTILS_HOE = register("capital_outils_hoe", Capital_outilsHoeItem::new);
		CAPITALE_ARMOR_HELMET = register("capitale_armor_helmet", CapitaleArmorItem.Helmet::new);
		CAPITALE_ARMOR_CHESTPLATE = register("capitale_armor_chestplate", CapitaleArmorItem.Chestplate::new);
		CAPITALE_ARMOR_LEGGINGS = register("capitale_armor_leggings", CapitaleArmorItem.Leggings::new);
		CAPITALE_ARMOR_BOOTS = register("capitale_armor_boots", CapitaleArmorItem.Boots::new);
		CAPITALAPPLE = register("capitalapple", CapitalappleItem::new);
		COBALT = register("cobalt", RubyItem::new);
		RUBI_PICKAXE = register("rubi_pickaxe", RubiPickaxeItem::new);
		RUBI_AXE = register("rubi_axe", RubiAxeItem::new);
		RUBI_SWORD = register("rubi_sword", RubiSwordItem::new);
		RUBI_SHOVEL = register("rubi_shovel", RubiShovelItem::new);
		RUBI_HOE = register("rubi_hoe", RubiHoeItem::new);
		RUBI_ARMOR_HELMET = register("rubi_armor_helmet", RubiArmorItem.Helmet::new);
		RUBI_ARMOR_CHESTPLATE = register("rubi_armor_chestplate", RubiArmorItem.Chestplate::new);
		RUBI_ARMOR_LEGGINGS = register("rubi_armor_leggings", RubiArmorItem.Leggings::new);
		RUBI_ARMOR_BOOTS = register("rubi_armor_boots", RubiArmorItem.Boots::new);
		CAPITALSTICK = register("capitalstick", CapitalstickItem::new);
		CABLOCK = block(CapitalModeModBlocks.CABLOCK);
		COBLOCK = block(CapitalModeModBlocks.COBLOCK);
		UN_EU = register("un_eu", UnEUItem::new);
		DIXEURO = register("dixeuro", DixeuroItem::new);
		CINQUANNTE_EU = register("cinquannte_eu", CinquannteEUItem::new);
		CENT_EU = register("cent_eu", CentEUItem::new);
		CINQCEN_EU = register("cinqcen_eu", CinqcenEUItem::new);
		AMELIORATEURLVL_2 = register("ameliorateurlvl_2", Ameliorateurlvl2Item::new);
		AMELIORATEURLVL_3 = register("ameliorateurlvl_3", Ameliorateurlvl3Item::new);
		AMELIORATEURLVL_4 = register("ameliorateurlvl_4", Ameliorateurlvl4Item::new);
		AMELIORATEURLVL_5 = register("ameliorateurlvl_5", Ameliorateurlvl5Item::new);
		SPEED_SWORD = register("speed_sword", SpeedSwordItem::new);
		CAPITAL_MACHINE = block(CapitalModeModBlocks.CAPITAL_MACHINE);
		AMELIORASTONE = register("ameliorastone", AmeliorastoneItem::new);
		SPEEDSTONE = register("speedstone", SpeedstoneItem::new);
		SPEEDPICKAXE = register("speedpickaxe", SpeedpickaxeItem::new);
		CAPITALHAMMER = register("capitalhammer", CapitalhammerItem::new);
		CAPITALWAND = register("capitalwand", CapitalwandItem::new);
		ULTIMASTONE = register("ultimastone", UltimastoneItem::new);
		BIGSWORD = register("bigsword", BigswordItem::new);
		AMELIORATEURNIV_6ITEM = register("ameliorateurniv_6item", Ameliorateurniv6itemItem::new);
		COBALT_HAMMER = register("cobalt_hammer", CobaltHammerItem::new);
		COBALTSPEEDSWORD = register("cobaltspeedsword", CobaltspeedswordItem::new);
		COBALTBIGWORD = register("cobaltbigword", CobaltbigwordItem::new);
		COBALTSPEEDPICKAXE = register("cobaltspeedpickaxe", CobaltspeedpickaxeItem::new);
		AMELIORATEURLVL_7 = register("ameliorateurlvl_7", Ameliorateurlvl7Item::new);
		MILLEEURO = register("milleeuro", MilleeuroItem::new);
		AMELIORATEURLVL_9 = register("ameliorateurlvl_9", Ameliorateurlvl9Item::new);
		AMELIORATEURLVL_8 = register("ameliorateurlvl_8", Ameliorateurlvl8Item::new);
		SUGILITE_BLOCK = block(CapitalModeModBlocks.SUGILITE_BLOCK);
		SUGILITE_PICKAXE = register("sugilite_pickaxe", SugilitePickaxeItem::new);
		SUGILITE_SHOVEL = register("sugilite_shovel", SugiliteShovelItem::new);
		SUGILITE_AXE = register("sugilite_axe", SugiliteAxeItem::new);
		SUGILITE = register("sugilite", SugiliteItem::new);
		SUGILITE_ARMOR_HELMET = register("sugilite_armor_helmet", SugiliteArmorItem.Helmet::new);
		SUGILITE_ARMOR_CHESTPLATE = register("sugilite_armor_chestplate", SugiliteArmorItem.Chestplate::new);
		SUGILITE_ARMOR_LEGGINGS = register("sugilite_armor_leggings", SugiliteArmorItem.Leggings::new);
		SUGILITE_ARMOR_BOOTS = register("sugilite_armor_boots", SugiliteArmorItem.Boots::new);
		SUGILITE_SWORD = register("sugilite_sword", SugiliteSwordItem::new);
		SUGILITE_HOE = register("sugilite_hoe", SugiliteHoeItem::new);
		AMELIORATEURLVL_10 = register("ameliorateurlvl_10", Ameliorateurlvl10Item::new);
		FONDERIE = block(CapitalModeModBlocks.FONDERIE);
		CAPITALFONDU_BUCKET = register("capitalfondu_bucket", CapitalfonduItem::new);
		BATONIRIDUIM = register("batoniriduim", BatoniriduimItem::new);
		ACHATCHUNK = register("achatchunk", AchatchunkItem::new);
		PERFECT_COAL = register("perfect_coal", PerfectCoalItem::new);
		COBALTFONDU_BUCKET = register("cobaltfondu_bucket", CobaltfonduItem::new);
		CAPITALPOWDER = register("capitalpowder", CapitalpowderItem::new);
		COBALTPOWDER = register("cobaltpowder", CobaltpowderItem::new);
		IRIDIUMPOWDER = register("iridiumpowder", IridiumpowderItem::new);
		IRIDFONDU_BUCKET = register("iridfondu_bucket", IridfonduItem::new);
		DEADSTONE = register("deadstone", DeadstoneItem::new);
		CAPITAL_FAUX = register("capital_faux", CapitalFauxItem::new);
		COBGDAGUE = register("cobgdague", CobgdagueItem::new);
		CAPITALDAGUE = register("capitaldague", CapitaldagueItem::new);
		FIRESTONE = register("firestone", FirestoneItem::new);
		IRIDIUMSPEEDSWORD = register("iridiumspeedsword", IridiumspeedswordItem::new);
		CAPITALSPEAR = register("capitalspear", CapitalspearItem::new);
		IRIDIUMHAMMER = register("iridiumhammer", IridiumhammerItem::new);
		IRIDIUMSPEEDPICKAXE = register("iridiumspeedpickaxe", IridiumspeedpickaxeItem::new);
		IRIDIUMBIGSWORD = register("iridiumbigsword", IridiumbigswordItem::new);
		GRANDCOEUR = register("grandcoeur", GrandcoeurItem::new);
		FANDECAPITAL = register("fandecapital", FandecapitalBlock.Item::new);
		BOURREDEFLECHES = register("bourredefleches", BourredeflechesItem::new);
		HYPERACTIF_1 = register("hyperactif_1", Hyperactif1Item::new);
		HYPERACTIF_2 = register("hyperactif_2", Hyperactif2Item::new);
		HYPERACTIF_3 = register("hyperactif_3", Hyperactif3Item::new);
		YEUXDECHAT = register("yeuxdechat", YeuxdechatItem::new);
		GRANDCOEUR_2 = register("grandcoeur_2", Grandcoeur2Item::new);
		GRANDCOEUR_3 = register("grandcoeur_3", Grandcoeur3Item::new);
		PETITSSOINS = register("petitssoins", PetitssoinsItem::new);
		CHUTELIBRE = register("chutelibre", ChutelibreItem::new);
		CAPITALSEED = register("capitalseed", CapitalseedItem::new);
		CAPITALPLANT = block(CapitalModeModBlocks.CAPITALPLANT);
		CAPITALPLANT_2 = block(CapitalModeModBlocks.CAPITALPLANT_2);
		CAPITALPLANT_3 = block(CapitalModeModBlocks.CAPITALPLANT_3);
		CAPITALPLANT_4 = block(CapitalModeModBlocks.CAPITALPLANT_4);
		DOLOMITEINGOT = register("dolomiteingot", DolomiteingotItem::new);
		DOLOMITEORE = block(CapitalModeModBlocks.DOLOMITEORE);
		ELECTRICFURNACE = block(CapitalModeModBlocks.ELECTRICFURNACE);
		DIMENSIONALMACHINE = block(CapitalModeModBlocks.DIMENSIONALMACHINE);
		PUISSANCEDEMONIAQUE = register("puissancedemoniaque", PuissancedemoniaqueItem::new);
		BATTERIE = block(CapitalModeModBlocks.BATTERIE);
		COAL_RANK = register("coal_rank", CoalrankItem::new);
		IRIDIUM_RANK = register("iridium_rank", IridiumrankItem::new);
		GOLD_RANK = register("gold_rank", GoldRankItem::new);
		COBALT_RANK = register("cobalt_rank", CobaltrankItem::new);
		DIAMOND_RANK = register("diamond_rank", DiamondrankItem::new);
		IRON_RANK = register("iron_rank", IronrankItem::new);
		NETHERITE_RANK = register("netherite_rank", NetheriterankItem::new);
		CAPITAL_RANK = register("capital_rank", CapitalrankItem::new);
		BANDAGE = register("bandage", BandageItem::new);
		ATM = block(CapitalModeModBlocks.ATM);
		COBALTSEED = register("cobaltseed", CobaltseedItem::new);
		COBALTPLANT = block(CapitalModeModBlocks.COBALTPLANT);
		COBALTPLANT_2 = block(CapitalModeModBlocks.COBALTPLANT_2);
		COBALTPLANT_3 = block(CapitalModeModBlocks.COBALTPLANT_3);
		COBALTPLANT_4 = block(CapitalModeModBlocks.COBALTPLANT_4);
		IRIDIUMSEED = register("iridiumseed", IridiumseedItem::new);
		IRIDIUMPLANT = block(CapitalModeModBlocks.IRIDIUMPLANT);
		IRIDIUMPLANT_2 = block(CapitalModeModBlocks.IRIDIUMPLANT_2);
		IRIDIUMPLANT_3 = block(CapitalModeModBlocks.IRIDIUMPLANT_3);
		IRIDIUMPLANT_4 = block(CapitalModeModBlocks.IRIDIUMPLANT_4);
		DOLOMITE_FARMLAND = block(CapitalModeModBlocks.DOLOMITE_FARMLAND);
		QUARRY = block(CapitalModeModBlocks.QUARRY);
		LIMITES = block(CapitalModeModBlocks.LIMITES);
		CAPITALE = block(CapitalModeModBlocks.CAPITALE);
		BIONICSWORD = register("bionicsword", BionicswordItem::new);
		BATTERIEEXTERNE = register("batterieexterne", BatterieexterneItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), CAPITALFONDU_BUCKET.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), COBALTFONDU_BUCKET.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), IRIDFONDU_BUCKET.get());
	}
}